name: "sphinx docs check"

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: docs/
      - uses: actions/upload-artifact@v1
        with:
          name: DocumentationHTML
          path: docs/_build/html

